const header = `<header class="site-header"><div class="shipping">Free shipping on all orders over $200 for a limited time</div><div class="header-main"><a class="brand" href="index.html"><span class="brand-figures">♟♟</span><span>OVERCOATS</span></a><label class="search"><span>⌕</span><input type="search" aria-label="Search products" placeholder="Search"></label><div class="icons"><button aria-label="Wishlist">♡<b>12</b></button><button aria-label="Account">♟</button><a href="checkout.html" aria-label="Cart">🛒<b>3</b></a></div></div><nav><a href="catalogue.html">All</a><a href="catalogue.html?group=mens">Mens</a><a href="catalogue.html?group=womens">Woman</a><a href="catalogue.html?group=kids">Kids</a><span></span><a href="about.html">About</a><a href="locator.html">Store Locator</a><a href="enquiry.html">Enquiry</a><a href="contact.html">Contact</a></nav></header>`;
const footer = `<footer class="site-footer"><a class="button" href="contact.html">Contact Us</a><div><h3>Customer Support</h3><a>Returns</a><a>Payments</a><a>Shipping</a><a>Terms &amp; Conditions</a><a>Privacy Policy</a></div><div><h3>Corporate Info</h3><a href="about.html">About Us</a><a>Brands</a><a>Affiliates</a><a>Investors</a><a>Cookies</a></div><div><h3>Gift Card</h3><a>Buy Gift Cards</a><a>Redeem Card</a><p class="payment">VISA<span>●</span>●</p><p class="social">● ◎ ● ♪</p></div></footer>`;
document.querySelector('#shared-header')?.replaceWith(document.createRange().createContextualFragment(header));
document.querySelector('#shared-footer')?.replaceWith(document.createRange().createContextualFragment(footer));
const imageFolders={women:'assets/images/women/',men:'assets/images/men/',kids:'assets/images/kids/'};
const imageFiles={women:['EDG0506244072.webp','360_F_420661462_gNPIK7Y1joHC4plNCzuti5au9Mq4uXOR.jpg','3933BROWN06LEADD_700x.webp','ART06-604_F_305.webp','c0e7b906ef9ac065cce01d33009e737485e40802_xxl-1.avif','istockphoto-1357329192-612x612.jpg','IMG_5472_cfe44351-a19c-44dd-9c51-027052cbcd8f.webp','umtLZPWhSBGjXiNDigC7VK.jpg','bkk29209_pale pink_xl.webp','oj1917-137p_check_1.webp','LCA0425TA51_01front.webp','436481.jpg'],men:['26SMEW02_4003_1.webp','318a3fca-b183-4e7b-9f51-1c396f725cb8.png','8c350630deb50b6fc290096a6db2304aaa758920.avif','Artboard11_11348eb5-e9ba-4e42-a787-76578390ac35_1024x.webp','I04A9965.webp','PERCIVAL_MENSWEAR_8_2e380db4-bb34-4cdc-9e90-9cb9038725c3.jpg','S285081_SIRGIIO_NAVY_1.webp','TILLMAN-NAVY-STATIC-PLAID_1_RM-524A-965E-8989.webp','ba216749-15e8-406f-b04a-e75b6a9c9e51.png','cmm24278_black_xl.webp','images - 2026-09-25T184410.583.jpeg','original.jpg'],kids:['21_56100330003_6.webp','21_56100340001_6.webp','21_56700100009_6.webp','38091992_fpx.jpeg','4573019_N220_MF_1.jpg','FullSizeRender_07b0c08f-f567-44f9-bcdf-647c904f15f7.webp','WNY9K_SQ1_0000000070_DARK_GREY_MDf.webp','a0962_893_boys_epiq_down_jacke_a.webp','original (2).jpg','original.jpg','s7-AI323969861001_alternate10.avif','teddy-fleece-jacket_raspberry_main.webp']};
const names={women:['Camden Wool Coat','Harper Belted Coat','Sienna Check Overcoat','Luna Puffer Jacket','Marlowe Trenchcoat','Evelyn Wrap Coat','Aspen Quilted Coat','Dahlia Longline Coat','Rosa Teddy Coat','Mila Tailored Coat','Sage Raincoat','Noor Double-Breasted Coat'],men:['Harrison Peacoat','Lennox Wool Overcoat','Mason Quilted Jacket','Ryder Field Coat','Theo Mac Coat','Winston Trenchcoat','Otto Puffer Jacket','Felix Herringbone Coat','Arlo Leather Jacket','Cole Parka','Bennett Car Coat','Hudson Check Coat'],kids:['Mia Mini Puffer','Noah Storm Jacket','Elsie Quilted Coat','Leo Winter Parka','Ava Teddy Coat','Kai Rain Jacket','Ruby Hooded Coat','Owen Puffer Coat','Isla Longline Coat','Luca Wool Coat','Zara Snow Jacket','Finn Sherpa Coat']};
const descriptions={women:['Warm wool blend, tailored fit','Soft-touch finish, everyday elegance','Classic pattern with a cosy lining'],men:['Structured warmth for cooler days','Smart outer layer in a wool blend','Weather-ready comfort and style'],kids:['Play-ready warmth with a soft lining','Cosy, lightweight and easy to move in','Built for little winter adventures']};
const price=(group,index)=>`R${(699+((index*317+group.length*143)%1900)).toLocaleString('en-ZA')}`;
let localImages={};
Object.entries(imageFolders).forEach(([group,folder])=>{localImages[group]=imageFiles[group].map(file=>`${folder}${file}`)});
function productCards(target,count=12){const el=document.querySelector(target);if(!el)return;const queryGroup=new URLSearchParams(location.search).get('group');const selected={mens:'men',womens:'women',kids:'kids'}[queryGroup];const groups=selected?Array(count).fill(selected):Array.from({length:count},(_,i)=>['women','men','kids'][i%3]);el.innerHTML=groups.map((group,i)=>{const productIndex=i%12;const src=localImages[group][productIndex];const productName=names[group][productIndex];const key=`${group}-${productIndex}`;return `<article class="product-card"><a href="product.html"><img src="${encodeURI(src)}" alt="${productName}" loading="lazy"><h3>${productName}</h3></a><small>${descriptions[group][productIndex%3]}</small><span class="cost">${price(group,productIndex)}</span><button class="heart" type="button" aria-label="Add ${productName} to favourites" aria-pressed="false" data-favourite="${key}">♡</button><button class="button add">Add to Cart</button></article>`}).join('')}
productCards('.home-products',4);productCards('.catalogue-products');
document.querySelectorAll('[data-favourite]').forEach(button=>{const saved=localStorage.getItem(button.dataset.favourite)==='true';button.classList.toggle('liked',saved);button.setAttribute('aria-pressed',saved);button.textContent=saved?'♥':'♡';button.addEventListener('click',()=>{const liked=button.getAttribute('aria-pressed')!=='true';button.setAttribute('aria-pressed',liked);button.classList.toggle('liked',liked);button.textContent=liked?'♥':'♡';localStorage.setItem(button.dataset.favourite,liked)})});
const group=new URLSearchParams(location.search).get('group');if(group){const title=document.querySelector('#catalogue-title');if(title)title.textContent=({mens:'Men’s Coats',womens:'Woman’s Coats',kids:'Kid’s Coats'})[group]||'All Coats';const hero=document.querySelector('#catalogue-hero');const choices={mens:'photo-1610652492500-ded49ceeb378',womens:'photo-1483985988355-763728e1935b',kids:'photo-1519238360530-aae0c85e4980'};if(hero&&choices[group])hero.src=img(choices[group])}
const stores=[['Overcoats Brentwood Park','31 Van Wyk Road, Brentwood Park, Benoni','photo-1548345680-7b9df65b1e26'],['Coat Corner Kempton Park','79 Pretoria Road, Kempton Park','photo-1524661135-423995f22d0b'],['Coat Corner Springs','29 5th Avenue, Springs','photo-1559595500-e15296bdbb48']];const storesEl=document.querySelector('.stores');if(storesEl)storesEl.innerHTML=stores.map(s=>`<article class="store"><h2>${s[0]}</h2><img src="${img(s[2])}" alt="Map for ${s[0]}"><p><strong>Address</strong><br><small>${s[1]}</small></p></article>`).join('');
